# Generated by Django 4.2.16 on 2024-09-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='description',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
